### PR TITLE
Added React.Router

### PR DESCRIPTION
**Pull request by ongmin**
**Temporary measure **- For reconcilation tomorrow.
- Webpack's package.json has been renamed to _package.json. 
- Gulp's package.json has been named at package.json.

### CODE REVIEW

**Comment by cbas** [comment]
Err would have preferred cleaning up 6a5f66895afb2527b90fb65c98224de2554827f6 to avoid stats spam.

**Comment by ongmin** [comment]
@cbas I still have 1.7m lines. :+1: Is it still possible after its a few commits behind? :confused:

**Comment by cbas** [comment]
You'll have to rewrite history to clean this up. Try this: http://stackoverflow.com/a/17824718

**Comment by ongmin** [comment]
ok thank you. guess I'm going to have to rewrite history into herstory.

**Comment by cbas** [comment]
Wut?

LOL apparently feminist revisionism is really a thing ... http://dictionary.reference.com/browse/herstory

:laughing:

**Pull request merged**
